name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  buildwin:
    name: BuildWin
    runs-on: "ubuntu-latest"
    steps:
      - name: GitCheckout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Instalacija
        run: sudo apt install g++-mingw-w64-x86-64 libfreetype6-dev
        
      - name: MingwVerzija
        run: |
          x86_64-w64-mingw32-g++ -v
          ls /usr/lib/gcc/x86_64-w64-mingw32/10-win32/libstdc++*

      - name: DownloadSFML
        run: |
          wget https://www.sfml-dev.org/files/SFML-2.5.1-windows-gcc-7.3.0-mingw-64-bit.zip
          unzip SFML-2.5.1-windows-gcc-7.3.0-mingw-64-bit.zip
          mv SFML-2.5.1 sfml

      - name: Compile
        run: |
          x86_64-w64-mingw32-g++ -DSFML_STATIC -std=c++14 -O2 -o sokoban.exe src/*.cpp -I sfml/include -L sfml/lib -lsfml-graphics-s -lsfml-window-s -lsfml-system-s -lfreetype -lopengl32 -lwinmm -lgdi32 -static-libstdc++ -static-libgcc

      - name: Archive
        run: |
          tar -czf sokoban-wind0ws-x86_64.tar.gz sokoban.exe resources
          zip -r sokoban-wind0ws-x86_64.zip sokoban.exe resources

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            sokoban-wind0ws-x86_64.tar.gz
            sokoban-wind0ws-x86_64.zip
        
  buildlinux:
    name: BuildLinux
    runs-on: "ubuntu-latest"
    steps:
      - name: GitCheckout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Instalacija
        run: sudo apt install libsfml-dev

      - name: GppVerzija
        run: g++ -v

      - name: Compile
        run: |
          make

      - name: Archive
        run: |
          tar -czf sokoban-linux-x86_64.tar.gz sokoban.out resources
          zip -r sokoban-linux-x86_64.zip sokoban.out resources

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            sokoban-linux-x86_64.tar.gz
            sokoban-linux-x86_64.zip
